default: Node.class TSP.class Assignment2.class

TSP.class: Tsp.java
	javac -g Tsp.java

Assignment2.class: assignmentP2.java
	javac -g assignmentP2.java

Node.class: Node.java
	javac -g Node.java

clean: 
	$(RM) *.class
